### ISSUE TITLE
While executing your code i am facing NameError max_seq_len in data_sst2.py  file

### ISSUE THREAD

**Issue by mansabshebi** [YJiangcm/SST-2-sentiment-analysis#1]
hi i am an ms scholar. i have seen your repo recently and tried to implement code for experience and insights. but facing this error 
![image](https://user-images.githubusercontent.com/35061811/101671040-c83da580-3a75-11eb-8bd6-9978508d8d01.png) kindly reply me as soon as possible and give your email too

**Comment by YJiangcm** [comment]
Hi, I have fixed the bug, and you could try again. By the way, if it still does not work, you may open the "run_bert.ipynb" file in Colab and run.

**Comment by mansabshebi** [comment]
> Hi, I have fixed the bug, and you could try again. By the way, if it still does not work, you may open the "run_bert.ipynb" file in Colab and run.

Thank you! its working now
