### ISSUE TITLE
model_train_validate_test() got an unexpected keyword argument 'max_seq_len'

### ISSUE THREAD

**Issue by mansabshebi** [YJiangcm/SST-2-sentiment-analysis#2]
while training run_Albert_model.ipynb I am facing this error 
![image](https://user-images.githubusercontent.com/35061811/101734989-fa392100-3ae2-11eb-99d4-2415db21df6c.png)

**Comment by YJiangcm** [comment]
I think you may use the code before updated. Please use the new version in the repository.
